name: Data Preprocessing

on:
  push:
    branches:
      - main

jobs:
  preprocess_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_kenny.py

    - name: Commit processed data
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add preprocessing/diabetes_preprocessing.csv
        git commit -m "Add processed data"
        git push
